# STYLING
set -g status-position top
set -g status-left-length 100

set -g status-left "#[fg={{colors.on_primary.default.hex}},nobold]#S #[fg={{colors.outline.default.hex}},nobold] | "

set -g window-status-current-format "#[fg={{colors.on_primary.default.hex}},bg={{colors.primary.default.hex}},bold] #I:#W "
set -g window-status-format "  #I:#W"

set -g message-style "fg={{colors.tertiary.default.hex}},bg=default"
set -g mode-style "fg={{colors.on_primary.default.hex}},bg={{colors.primary.default.hex}}"

set -g pane-border-style "fg={{colors.outline.default.hex}}"
set -g pane-active-border-style "fg={{colors.primary.default.hex}}"
